spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY:sk-eefc8e077bca40dbadcca058ec3d5cb6}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
          max-tokens: 2000
          top-p: 0.9
          frequency-penalty: 0.0
          presence-penalty: 0.0

logging:
  level:
    org.springframework.ai: DEBUG
  config: classpath:logback.xml

server:
  port: 8080